language: php
php:
    - 5.3
    - 5.4
before_script:
    # gearman
    - sudo apt-get install gearman-server libgearman-dev
    - printf "\n"| sudo pecl install gearman
    - sudo /etc/init.d/gearman-job-server start
    # worker
    - php -f tests/worker.php >/dev/null 2>/dev/null &


