language: php
php:
    - 5.3
    - 5.4
before_script:
    # gearman
    - sudo apt-get install gearman-server libgearman-dev
    - ls /etc/init.d
    - sudo /etc/init.d/gearman-job-server restart
    - printf "\n"| pecl install gearman
    # worker
    - php -f tests/worker.php >/dev/null 2>/dev/null &


